version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kek
    ports:
      - 5432:5432
    hostname: db
  # monitoring
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
  telegraf:
    image: telegraf
    links:
      - influxdb
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/conf/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    links:
      - influxdb
  kek-server:
    image: kek-server-v2/kek-server
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    container_name: kek-server
    ports:
      - "8080:8080"
    volumes:
      - ./config/local.yaml:/config/config.yaml
      - ./migrations:/config/migrations
    command: kek-server --conf /config/config.yaml
    restart: always
    depends_on:
      - "db"
  kek-server2:
    image: kek-server-v2/kek-server
    container_name: kek-server-2
    ports:
      - "9090:9090"
    volumes:
      - ./config/local-2.yaml:/config/config.yaml
    command: kek-server --conf /config/config.yaml
    restart: always
    depends_on:
      - "db"