# config file version
apiVersion: 1

datasources:
  - name: influxdb
    isDefault: true
    type: influxdb
    access: proxy
    database: telegraf
    url: http://influxdb:8086
    jsonData:
      timeInterval: "10s"
